create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  app_version text,
  rating integer not null,
  comment text not null,
  approved boolean not null default false,
  display_name text,
  allow_publish boolean not null default false,
  source text,
  export_type text,
  rejected boolean not null default false,
  developer_comment text,
  developer_comment_visible boolean not null default false
);
