create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,

  created_at timestamp with time zone not null default now(),

  name text,
  email text,
  message text not null,

  resolved boolean not null default false,

  category text,
  app_version text,

  reply_memo text,
  replied_at timestamp with time zone
);