import type { Frame, FramePolygonPoints, FrameTiltValue, Page } from "./types";
import { createInnerLockedFrame } from "./presets";

export type TemplateDefinition = {
  id: string;
  name: string;
  frameCount: number;
  page: Page;
};

function createTemplateFrame(
  id: number,
  x: number,
  y: number,
  w: number,
  h: number,
  topTilt: FrameTiltValue = 0,
  rightTilt: FrameTiltValue = 0,
  bottomTilt: FrameTiltValue = 0,
  leftTilt: FrameTiltValue = 0,
  points?: FramePolygonPoints,
  borderEnabled: boolean = true
): Frame {
  return {
    id,
    x,
    y,
    w,
    h,
    borderEnabled,
    image: null,
    imageOffsetX: 0,
    imageOffsetY: 0,
    imageScale: 1,
    imageNaturalWidth: 0,
    imageNaturalHeight: 0,
    topTilt,
    rightTilt,
    bottomTilt,
    leftTilt,
    ...(points ? { points } : {}),
  };
}

function createTemplatePage(id: number, frames: Frame[]): Page {
  return {
    id,
    visible: true,
    frames: [createInnerLockedFrame(), ...frames],
    bubbles: [],
    sounds: [],
  };
}

export const TEMPLATE_DEFINITIONS: TemplateDefinition[] = [
  {
    id: "template-1-1",
    name: "テンプレ1_1",
    frameCount: 1,
    page: createTemplatePage(-1001, [
      createTemplateFrame(
        -100001,
        5,
        5,
        90,
        90,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        undefined,
        true
      ),
    ]),
  },
  {
    id: "template-2-1",
    name: "テンプレ2_1",
    frameCount: 2,
    page: createTemplatePage(-1002, [
      createTemplateFrame(
        -100002,
        5,
        5,
        90,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 5 },
          { x: 95, y: 5 },
          { x: 95, y: 50 },
          { x: 5, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100003,
        5,
        50,
        90,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 50 },
          { x: 95, y: 50 },
          { x: 95, y: 95 },
          { x: 5, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
    ]),
  },
  {
    id: "template-3-1",
    name: "テンプレ3_1",
    frameCount: 3,
    page: createTemplatePage(-1003, [
      createTemplateFrame(
        -100004,
        5,
        5,
        90,
        30,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 5 },
          { x: 95, y: 5 },
          { x: 95, y: 35 },
          { x: 5, y: 35 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100005,
        5,
        35,
        90,
        30,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 35 },
          { x: 95, y: 35 },
          { x: 95, y: 65 },
          { x: 5, y: 65 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100006,
        5,
        65,
        90,
        30,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 65 },
          { x: 95, y: 65 },
          { x: 95, y: 95 },
          { x: 5, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
    ]),
  },
  {
    id: "template-3-2",
    name: "テンプレ3_2",
    frameCount: 3,
    page: createTemplatePage(-1004, [
      createTemplateFrame(
        -100007,
        50,
        5,
        45,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 50, y: 5 },
          { x: 95, y: 5 },
          { x: 95, y: 50 },
          { x: 50, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100008,
        5,
        5,
        45,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 5 },
          { x: 50, y: 5 },
          { x: 50, y: 50 },
          { x: 5, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100009,
        5,
        50,
        90,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 50 },
          { x: 95, y: 50 },
          { x: 95, y: 95 },
          { x: 5, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
    ]),
  },
  {
    id: "template-4-1",
    name: "テンプレ4_1",
    frameCount: 4,
    page: createTemplatePage(-1006, [
      createTemplateFrame(
        -100013,
        50,
        5,
        45,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 50, y: 5 },
          { x: 95, y: 5 },
          { x: 95, y: 50 },
          { x: 50, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100014,
        5,
        5,
        45,
        22.5,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 5 },
          { x: 50, y: 5 },
          { x: 50, y: 27.5 },
          { x: 5, y: 27.5 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100015,
        5,
        27.5,
        45,
        22.5,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 27.5 },
          { x: 50, y: 27.5 },
          { x: 50, y: 50 },
          { x: 5, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100016,
        5,
        50,
        90,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 50 },
          { x: 95, y: 50 },
          { x: 95, y: 95 },
          { x: 5, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
    ]),
  },
  {
    id: "template-4-2",
    name: "テンプレ4_2",
    frameCount: 4,
    page: createTemplatePage(-1008, [
      createTemplateFrame(
        -100021,
        50,
        5,
        45,
        22.5,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 50, y: 5 },
          { x: 95, y: 5 },
          { x: 95, y: 27.5 },
          { x: 50, y: 27.5 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100022,
        50,
        27.5,
        45,
        22.5,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 50, y: 27.5 },
          { x: 95, y: 27.5 },
          { x: 95, y: 50 },
          { x: 50, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100023,
        5,
        5,
        45,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 5 },
          { x: 50, y: 5 },
          { x: 50, y: 50 },
          { x: 5, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100024,
        5,
        50,
        90,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 50 },
          { x: 95, y: 50 },
          { x: 95, y: 95 },
          { x: 5, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
    ]),
  },
  {
    id: "template-4-3",
    name: "テンプレ4_3",
    frameCount: 4,
    page: createTemplatePage(-1010, [
      createTemplateFrame(
        -100029,
        5,
        5,
        90,
        25,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 5 },
          { x: 95, y: 5 },
          { x: 95, y: 30 },
          { x: 5, y: 30 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100030,
        55,
        30,
        40,
        20,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 55, y: 30 },
          { x: 95, y: 30 },
          { x: 95, y: 50 },
          { x: 55, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100031,
        5,
        30,
        50,
        20,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 30 },
          { x: 55, y: 30 },
          { x: 55, y: 50 },
          { x: 5, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100032,
        5,
        50,
        90,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 50 },
          { x: 95, y: 50 },
          { x: 95, y: 95 },
          { x: 5, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
    ]),
  },
  {
    id: "template-4-4",
    name: "テンプレ4_4",
    frameCount: 4,
    page: createTemplatePage(-1012, [
      createTemplateFrame(
        -100037,
        5,
        5,
        90,
        25,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 5 },
          { x: 95, y: 5 },
          { x: 95, y: 30 },
          { x: 5, y: 30 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100038,
        45,
        30,
        50,
        20,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 45, y: 30 },
          { x: 95, y: 30 },
          { x: 95, y: 50 },
          { x: 45, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100039,
        5,
        30,
        40,
        20,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 30 },
          { x: 45, y: 30 },
          { x: 45, y: 50 },
          { x: 5, y: 50 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100040,
        5,
        50,
        90,
        45,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 50 },
          { x: 95, y: 50 },
          { x: 95, y: 95 },
          { x: 5, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
    ]),
  },
  {
    id: "template-5-1",
    name: "テンプレ5_1",
    frameCount: 5,
    page: createTemplatePage(-1014, [
      createTemplateFrame(
        -100045,
        55,
        5,
        40,
        20,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 55, y: 5 },
          { x: 95, y: 5 },
          { x: 95, y: 25 },
          { x: 55, y: 25 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100046,
        4.999999999999993,
        5,
        49.99999999999996,
        20,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 4.999999999999993, y: 5 },
          { x: 54.99999999999995, y: 5 },
          { x: 54.99999999999995, y: 25 },
          { x: 4.999999999999993, y: 25 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100047,
        5,
        25,
        90,
        35,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 25 },
          { x: 95, y: 25 },
          { x: 95, y: 60 },
          { x: 5, y: 60 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100048,
        45,
        60,
        50,
        35,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 45, y: 60 },
          { x: 95, y: 60 },
          { x: 95, y: 95 },
          { x: 45, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100049,
        5,
        60,
        40.00000000000001,
        35,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 60 },
          { x: 45.00000000000001, y: 60 },
          { x: 45.00000000000001, y: 95 },
          { x: 5, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
    ]),
  },
  {
    id: "template-5-2",
    name: "テンプレ5_2",
    frameCount: 5,
    page: createTemplatePage(-1016, [
      createTemplateFrame(
        -100055,
        45,
        5,
        50,
        20,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 45, y: 5 },
          { x: 95, y: 5 },
          { x: 95, y: 25 },
          { x: 45, y: 25 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100056,
        4.999999999999993,
        5,
        39.99999999999996,
        20,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 4.999999999999993, y: 5 },
          { x: 44.99999999999995, y: 5 },
          { x: 44.99999999999995, y: 25 },
          { x: 4.999999999999993, y: 25 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100057,
        5,
        25,
        90,
        35,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 25 },
          { x: 95, y: 25 },
          { x: 95, y: 60 },
          { x: 5, y: 60 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100058,
        55,
        60,
        40,
        35,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 55, y: 60 },
          { x: 95, y: 60 },
          { x: 95, y: 95 },
          { x: 55, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
      createTemplateFrame(
        -100059,
        5,
        60,
        50,
        35,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        0 as FrameTiltValue,
        [
          { x: 5, y: 60 },
          { x: 55, y: 60 },
          { x: 55, y: 95 },
          { x: 5, y: 95 },
        ] as FramePolygonPoints,
        true
      ),
    ]),
  },
];
